### ISSUE TITLE
Bug: Bulk ack truncated by NetworkError / CORS

### ISSUE THREAD

**Issue by hhramberg** [Uninett/Argus-frontend#452]
**Describe the bug**

Bulk acknowledgement of multiple Argus incidents is causes CORS and/or NetworkError.

```
catched network error Error: Network Error
    exports createError.js:16
    onerror xhr.js:99
 Error: Failed to post incident ack: Error: Network Error
    value client.ts:611
    value client.ts:106
[apiinterceptor.tsx:43:18](https://secret.argus.com/static/js/components/apiinterceptor.tsx)
    e apiinterceptor.tsx:43
    value client.ts:109
    value client.ts:108
```

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://secret.argus.com/api/v1/incidents/26915/acks/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.
```

**To Reproduce**
1. Go to Argus incident page.
2. Click on "select all" incidents.
3. Click on "Ack" to acknowledge all incidents currently selected.
4. See error reported by Argus.

**Expected behavior**
All selected Argus incidents to be successfully acknowledged without any network errors.

**Screenshots**
![argus_bulk_ack_issue](https://user-images.githubusercontent.com/57575546/198524429-f24066f4-71c8-47b9-a4ee-c890eab55c40.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux 22.0.0
 - Browser: Firefox
 - Version: 105.0.3 (64-bit)

**Additional context**
Argus version: Backend v.1.8.0, API v1(stable), frontend v.1.6.1

**Comment by hhramberg** [comment]
After some further testing it appears that the error occurs when bulk inserting 5 or more incidents.

**Comment by johannaengland** [comment]
Fixed by #480

**Comment by podliashanyk** [comment]
Bug is still relevant.

### Bug update:
Bulk close and bulk reopen are also affected. **Bulk ticket update works fine** and without errors, regardless how many incidents are being updated.
